name: Run Gold Price Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install requests

      - name: Run bot
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          RUBIK_TOKEN: ${{ secrets.RUBIK_TOKEN }}
        run: |
          python main.py
